# ------------------------------------------------------------------------------
# Problem 12
# ------------------------------------------------------------------------------
# The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.
# The sequence of triangle numbers is generated by adding the natural numbers.
# So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first
 # ten terms would be:
#
#               1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
#
# Let us list the factors of the first seven triangle numbers:
#
#        1: 1
#        3: 1,3
#        6: 1,2,3,6
#       10: 1,2,5,10
#       15: 1,3,5,15
#       21: 1,3,7,21
#       28: 1,2,4,7,14,28
#
# We can see that 28 is the first triangle number to have over five divisors.
#
# What is the value of the first triangle number to have over five hundred divisors?
# ------------------------------------------------------------------------------

number = 0
factors = 0
counter = 1

until factors > 500 do
  factors = 0
  number += counter
  
  for x in 1..number
    if number % x == 0
      factors += 1
    end
  end

  counter +=1
end

puts number

# ------------------------------------------------------------------------------
# Answer:
# ------------------------------------------------------------------------------
