# ------------------------------------------------------------------------------
# Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.
# ------------------------------------------------------------------------------

fib_array = [1,2]
i = 1
sum = 0

while fib_array[i] < 4000000 do
  fib_array << fib_array[i] + fib_array[i-1]
  if fib_array[i]%2 == 0
    sum += fib_array[i]
  end
  i +=1
end

puts sum

# ------------------------------------------------------------------------------
# Answer: 4613732
# ------------------------------------------------------------------------------
